<a href="https://colab.research.google.com/github/kevin4moe/DataSciencePracticas/blob/main/FP_Tarea_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Problema 1
Construya una matriz cuadrada de dimensión 10 cuyos elemenstos satisfagan las consiciones

In [ ]:
# Definimos el tamaño de la matriz
n = 10

# Creamos una matriz de ceros nxn
A = np.zeros((n, n), dtype=int)

# Siguiente las condiciones creamos rellenamos la matriz
for i in range(n):
    for j in range(n):
        A[i, j] = j - i + 1 # Las variables i y j empiezan en 0, por eso debemos sumar 1 para cumplir con A_{1,1}=1

print("Matrix A:")
print(A)

Matrix A:
[[ 1  2  3  4  5  6  7  8  9]
 [ 0  1  2  3  4  5  6  7  8]
 [-1  0  1  2  3  4  5  6  7]
 [-2 -1  0  1  2  3  4  5  6]
 [-3 -2 -1  0  1  2  3  4  5]
 [-4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3]
 [-6 -5 -4 -3 -2 -1  0  1  2]
 [-7 -6 -5 -4 -3 -2 -1  0  1]]


# Problema 2
Construya una matriz cuadrada de dimensión n, por fijar de manera arbitraria, cuyos elementos satisfagan las condiciones

In [ ]:
from random import randint as rnd
num = rnd(10, 20)
print(num)

12


In [ ]:
from random import randint as rnd
import numpy as np

# Creamos un número pseudo aleatorio del 10 al 20
num = rnd(10, 20)

# Definimos el tamaño de la matriz
n = num

# Creamos una matriz de ceros nxn
A = np.zeros((n, n), dtype=int)

# Siguiente las condiciones creamos rellenamos la matriz
for i in range(n):
    for j in range(n):
        A[i, j] = j - i + 1 # Las variables i y j empiezan en 0, por eso debemos sumar 1 para cumplir con A_{1,1}=1

print(f"Matrix A {n}x{n}:")
print(A)

Matrix A 15x15:
[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
 [ -1   0   1   2   3   4   5   6   7   8   9  10  11  12  13]
 [ -2  -1   0   1   2   3   4   5   6   7   8   9  10  11  12]
 [ -3  -2  -1   0   1   2   3   4   5   6   7   8   9  10  11]
 [ -4  -3  -2  -1   0   1   2   3   4   5   6   7   8   9  10]
 [ -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7   8   9]
 [ -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7   8]
 [ -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7]
 [ -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6]
 [ -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5]
 [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4]
 [-11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3]
 [-12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2]
 [-13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1]]


# Problema 3
El juego de SUDOKU consiste en rellenar una matriz de 9x9 particionada en 9 bloques o submatrices de 3x3. La meta es rellenar la matriz de tal forma que los números del 1 al 9 aparezcan solamente una vez en cada fila y en cada columna de la matriz de 9x9 y al mismo tiempo cada submatriz de 3x3 contenga los números del 1 al 9.

**(a)** Proponga un algoritmo y su correspondiente código que determine si una matriz es un SUDOKU completado.

**(b)** Proponga un algoritmo y su correspondiente código, que reciba una de estas matrices con una única posición sin establecer en cada fila y cada columna que será reemplazada con un cero con el objeto de identificarla.

In [ ]:
def is_valid_sudoku(board):
    # Valida que se cumpla la condición
    def is_valid_block(block):
        return sorted(block) == list(range(1, 10)) # Realiza una comparación entre ambas listas para verificar que el bloque en cuestion tenga cada número y solo una vez

    def get_block(board, row, col):
        # Extrae un bloque de 3x3
        block = [] # Se guarda el bloque como una lista
        # Calcula la posición del bloque
        start_row, start_col = row - row % 3, col - col % 3
        for i in range(3):
            for j in range(3):
                block.append(board[start_row + i][start_col + j])
        return block

    # Check all rows
    for row in range(9):
        if not is_valid_block(board[row]):
            return False

    # Check all columns
    for col in range(9):
        if not is_valid_block([board[row][col] for row in range(9)]):
            return False

    # Check all 3x3 blocks
    for row in range(0, 9, 3):
        for col in range(0, 9, 3):
            if not is_valid_block(get_block(board, row, col)):
                return False

    return True

# Example usage
sudoku_board = [
    [4, 8, 3, 2, 7, 1, 6, 9, 5],
    [9, 7, 6, 4, 8, 5, 3, 2, 1],
    [5, 2, 1, 3, 9, 6, 4, 7, 8],
    [2, 9, 4, 6, 5, 8, 1, 3, 7],
    [1, 3, 8, 9, 2, 7, 5, 6, 4],
    [6, 5, 7, 1, 3, 4, 9, 8, 2],
    [8, 4, 2, 5, 6, 3, 7, 1, 9],
    [3, 1, 9, 7, 4, 2, 8, 5, 6],
    [7, 6, 5, 8, 1, 9, 2, 4, 3],
]

print(is_valid_sudoku(sudoku_board))  # Output: True

True


# Problema 4

In [ ]:
from random import randint as rnd
import pandas as pd
import numpy as np

def dice_roll(n):
    df = pd.DataFrame(columns=['Dice 1', 'Dice 2', 'Dice 3'])

    for i in range(n):
        # Creamos un número pseudo aleatorio del 1 al 6
        df = df._append({'Dice 1': rnd(1, 6), 'Dice 2': rnd(1, 6), 'Dice 3': rnd(1, 6)}, ignore_index=True)

    return df

In [ ]:
n = 1000
df = dice_roll(n)

# Crea una tercer columna que compare los datos de los tres dados
df['Same'] = (df['Dice 1'] == df['Dice 2']) & (df['Dice 1'] == df['Dice 3'] )

# Calculamos el numero de eventos identicos
test_mil = np.where(df['Same'] == True)[0].size
test_mil = (n - test_mil)/n

print(f'Probabilidad de que los tres eventos sean distintos: {test_mil}%')

Probabilidad de que los tres eventos sean distintos: 0.971%


In [ ]:
n = 100000
df = dice_roll(n)

# Crea una tercer columna que compare los datos de los tres dados
df['Same'] = (df['Dice 1'] == df['Dice 2']) & (df['Dice 1'] == df['Dice 3'] )

# Calculamos el numero de eventos identicos
test_mil = np.where(df['Same'] == True)[0].size
test_mil = (n - test_mil)/n

print(f'Probabilidad de que los tres eventos sean distintos: {test_mil}%')

Probabilidad de que los tres eventos sean distintos: 0.97246%


# Problema 5

In [ ]:
from random import randint as rnd
import pandas as pd
import numpy as np

def door_game():
    doors = [1, 2, 3]
    price_door = rnd(1, 3)
    random_dude_option = rnd(1, 3)

    doors.remove(price_door)

    if price_door == random_dude_option:
        doors.remove(doors[rnd(0,1)])
    else:
        doors.remove(random_dude_option)

    return [doors[0], random_dude_option, price_door]



In [ ]:
n = 1000000
games = np.array([door_game() for i in range(n)])

df = pd.DataFrame(data=games, columns=['Puerta Abierta', 'Primera Puerta Selecionada', 'Puerta Ganadora'])
df

Puerta Abierta  Primera Puerta Selecionada  Puerta Ganadora
0                    3                           2                1
1                    3                           2                1
2                    3                           1                1
3                    1                           2                3
4                    1                           2                2
...                ...                         ...              ...
999995               3                           2                1
999996               2                           3                1
999997               2                           1                3
999998               2                           1                1
999999               2                           3                3

[1000000 rows x 3 columns]

In [ ]:
df['Gana?'] = (df['Primera Puerta Selecionada'] == df['Puerta Ganadora'] )

test = np.where(df['Gana?'] == True)[0].size

print(f'Probabilidad de ganar si no cambia la puerta que eliguió primero: {(test)/n}%')
print(f'Probabilidad de ganar si cambia la puerta que eliguió primero: {(n - test)/n}%')

Probabilidad de ganar si no cambia la puerta que eliguió primero: 0.333723%
Probabilidad de ganar si cambia la puerta que eliguió primero: 0.666277%
